config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'pages/about'

  resources :links do
    resources :comments, only: [:create, :destroy]
    member do
      put "upvote"
      put "downvote"
    end
  end

  root "links#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :owner, class_name: "User", foreign_key: :user_id
  belongs_to :link
  validates :body, presence: true
end

app/models/link.rb
class Link < ApplicationRecord
  belongs_to :owner, class_name: "User", foreign_key: :user_id
  has_many :comments
  acts_as_votable
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :links
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update , keys: [:name])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!

  def create
    @link = Link.find(params[:link_id])
    @comment = @link.comments.new(comment_params)
    @comment.owner = current_user
    
    if @comment.save
      redirect_to :back, notice: 'Comment was successfully created.'
    else
      redirect_to :back, alert: @comment.errors.full_messages.to_sentence
    end
  end
  
  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    redirect_to :back, notice: 'Comment was successfully destroyed.'
  end

  private
    def comment_params
      params.require(:comment).permit(:link_id, :body)
    end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  before_action :set_link, only: [:show, :upvote, :downvote]
  before_action :set_link_for_owner, only: [:edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  # GET /links
  # GET /links.json
  def index
    @links = Link.all
  end

  # GET /links/1
  # GET /links/1.json
  def show
  end

  # GET /links/new
  def new
    @link = current_user.links.build
  end

  # GET /links/1/edit
  def edit
  end

  # POST /links
  # POST /links.json
  def create
    @link = current_user.links.build(link_params)

    respond_to do |format|
      if @link.save
        format.html { redirect_to @link, notice: 'Link was successfully created.' }
        format.json { render :show, status: :created, location: @link }
      else
        format.html { render :new }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /links/1
  # PATCH/PUT /links/1.json
  def update
    respond_to do |format|
      if @link.update(link_params)
        format.html { redirect_to @link, notice: 'Link was successfully updated.' }
        format.json { render :show, status: :ok, location: @link }
      else
        format.html { render :edit }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /links/1
  # DELETE /links/1.json
  def destroy
    @link.destroy
    respond_to do |format|
      format.html { redirect_to links_url, notice: 'Link was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def upvote
    @link.upvote_by current_user
    redirect_to :back
  end

  def downvote
    @link.downvote_by current_user
    redirect_to :back
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_link
      @link = Link.find(params[:id])
    end

    def set_link_for_owner
      @link = current_user.links.find_by(id: params[:id])
      redirect_to :back, alert: "Unauthorized access!" if @link.nil?
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def link_params
      params.require(:link).permit(:title, :url)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/comments/_comment.html.haml
.row
  .col-md-8
    .comment
      .pull-left
        %p.lead= comment.body
        :erb
          <p><small>Submitted <strong><%= time_ago_in_words(comment.created_at) %> ago</strong>
              by <%= comment.owner.name %><small></p>

      .btn-group.pull-right
        - if comment.owner == current_user
          = link_to 'Delete', link_comment_path(comment.link, comment), 
            method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-sm btn-default"

app/views/common/_flash_messages.html.haml
- alert_classes = { notice: "success", alert: "danger" }
- flash.each do |type, message|
  %div{ class: "alert alert-#{ alert_classes[type.to_sym] || "info"} alert-dismissible", "role": "alert" } 
    %button{ "type": "button", class: "close", "data-dismiss": "alert", "aria-lable": "Close" }
      %span{ "aria-hidden": "true" } &times;
    = message

app/views/common/_footer.html.haml
%footer.text-center{ "style": "margin-top: 75px" }
  %hr
  %p
    Raddit
    %br/
    By
    %a{:href => "http://coopermaa2nd.blogspot.com", :target => "_blank"} coopermaa

app/views/common/_navbar.html.haml
%nav.navbar.navbar-inverse.navbar-fixed-top
  .container
    .navbar-header
      %button.navbar-toggle.collapsed{ "type": "button", "data-toggle": "collapse", |
      "data-target": "#navbar", "aria-expanded": "false" }
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to "Raddit", root_path, class: "navbar-brand"
     
    #navbar.collapse.navbar-collapse
      %ul.nav.navbar-nav.navbar-right
        - if user_signed_in?
          %li= link_to "Submit link", new_link_path
          %li= link_to "帳號", edit_user_registration_path
          %li= link_to "登出", destroy_user_session_path, method: :delete
        - else
          %li= link_to "註冊", new_user_registration_path
          %li= link_to "登入", new_user_session_path
        %li= link_to "About", pages_about_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{content: "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{ "name": "viewport", "content": "width=device-width, initial-scale=1"}
    %title Raddit
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render "common/navbar"
    .container
      = render "common/flash_messages"
      = yield
      = render "common/footer"

app/views/links/_form.html.haml
= form_for @link do |f|
  - if @link.errors.any?
    #error_explanation
      %h2= "#{pluralize(@link.errors.count, "error")} prohibited this link from being saved:"
      %ul
        - @link.errors.full_messages.each do |msg|
          %li= msg

  .form-group
    = f.label :title
    = f.text_field :title, class: "form-control"
  .form-group
    = f.label :url
    = f.text_field :url, class: "form-control"
  .form-group
    = f.submit 'Save', class: "btn btn-warning"

app/views/links/edit.html.haml
%h1 Editing link

= render 'form'

= link_to 'Show', @link
\|
= link_to 'Back', links_path

app/views/links/index.html.haml
- @links.each do |link|
  .link.row
    %h2
      =link_to link.title, link
      %br
      %small= "Submitted #{ time_ago_in_words(link.created_at) } by #{link.owner.name}"

    .btn-group
      %a.btn.btn-primary.btn-sm{ "href": link.url } Visit Link
      = link_to upvote_link_path(link), method: :put, class: "btn btn-default btn-sm" do
        %span.glyphicon.glyphicon-chevron-up
        Upvote
        = link.get_upvotes.size

      = link_to downvote_link_path(link), method: :put, class: "btn btn-default btn-sm" do
        %span.glyphicon.glyphicon-chevron-down
        Downvote
        = link.get_downvotes.size

app/views/links/new.html.haml
%h1 Submit link

= render 'form'

= link_to 'Back', links_path

app/views/links/show.html.haml
.row
  .col-md-8
    %h1
      = link_to @link.title, @link.url
      %br
        %small= "Submitted #{ time_ago_in_words(@link.created_at) } by #{@link.owner.name}"

    .btn-group
      %a.btn.btn-primary{ "href": @link.url } Visit Link

    .btn-group
      - if @link.owner == current_user
        = link_to "Edit", edit_link_path(@link), class: "btn btn-default"
        = link_to "Delete", @link, class: "btn btn-default",
          :method => :delete, :data => { :confirm => 'Are you sure?' }

    .btn-group.pull-right
      = link_to upvote_link_path(@link), method: :put, class: "btn btn-default btn-sm" do
        %span.glyphicon.glyphicon-chevron-up
        Upvote
        = @link.get_upvotes.size

      = link_to downvote_link_path(@link), method: :put, class: "btn btn-default btn-sm" do
        %span.glyphicon.glyphicon-chevron-down
        Downvote
        = @link.get_downvotes.size

.row
  .col-md-8
    %h3.comments_title
      = "#{@link.comments.count} Comments"

= render @link.comments

.row
  .col-md-8
    = simple_form_for [@link, Comment.new]  do |f|
      .form-group
        = f.text_area :body, class: "form-control"
      .form-group
        = f.submit "Add Comment", class: "btn btn-primary"

app/views/pages/about.html.haml
.well
  %h2 關於本站
  %ul
    %li
      這個應用程式是照著
      %a{:href => "https://mackenziechild.me/12-in-12/1/"} Week 1: How To Build A Reddit Clone With Rails 4
      這個教學影片一步步完成的
    %li
      程式碼網址:
      %a{:href => "https://github.com/coopermaa/raddit"} https://github.com/coopermaa/raddit
    %li 程式若有 Bug，歡迎送 Pull Request